export const afterError = (context) => {
  // handle me!
};
